# Dockerfile.test
FROM node:lts

# Create and change to the app directory
WORKDIR /home/node/app

# Copy package.json and package-lock.json
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy the rest of the application code
COPY . .

# Set environment variables
ENV NODE_ENV=test

# Start the tests
CMD ["npm", "run", "test"]
