# Dockerfile.db
FROM postgres:14

# Set environment variables
ENV POSTGRES_USER=${POSTGRES_USER}
ENV POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
ENV POSTGRES_DB=${POSTGRES_DB}

# Copy initialization scripts
COPY ./init_data /docker-entrypoint-initdb.d
