# Dockerfile.web
FROM node:lts

# Create and change to the app directory
WORKDIR /home/node/app

# Copy package.json and package-lock.json
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy the rest of the application code
COPY . .

# Set environment variables
ENV NODE_ENV=development
# Set environment variables
ENV POSTGRES_USER=${POSTGRES_USER}
ENV POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
ENV POSTGRES_DB=${POSTGRES_DB}
ENV SESSION_SECRET=${SESSION_SECRET}


# Expose the application port
EXPOSE 3000

# Start the application
CMD ["npm", "run", "start"]
